chore(core): Move 'unique' field into GenesisHeader
ceramicnetwork/js-ceramic pull request #1148
Opened 2021-03-22 20:45 UTC by stbrody

2021-03-22 21:00 UTC, stbrody commented
@oed do you know what's going on with the 3id test?  I assume the issue is that the vectors need to be regenerated since the JWS's will be different, although the way its failing looks different from what I would have expected.

If the issue is indeed just that the vectors need to be regenerated, is there an easy way to do that off of my working branch without needing to do a release first?

2021-03-23 07:41 UTC, oed commented
> I assume the issue is that the vectors need to be regenerated since the JWS's will be different, although the way its failing looks different from what I would have expected.

Ehm, this is **not** ok. We can't break the http api. Looks like it's an issue with how the deterministic flag is passed to the body of http requests. Can you make this change such that the http api works with the old way of passing the deterministic flag?

2021-03-23 08:53 UTC, oed commented
I fixed the issue by modifying the http request response mock.

Question: What will happen if someone now makes a http request with the `unique` property? Will it result in the same Ceramic document or a different one?

2021-03-23 09:52 UTC, oed requested changes
Ok, this is a problem. These two requests need to generate the same docid, otherwise things will break.

**Request 1, no unique**
```sh
curl https://ceramic-clay.3boxlabs.com/api/v0/documents -X POST -d '{
   "doctype": "tile",
   "genesis": {
     "header": {
       "family": "test",
       "controllers": ["did:key:z6MkfZ6S4NVVTEuts8o5xFzRMR8eC6Y1bngoBQNnXiCvhH8H"]
     }
   },
   "docOpts": { "publish": false, "anchor": false }
 }' -H "Content-Type: application/json"

{"docId":"k2t6wyfsu4pg2qvoorchoj23e8hf3eiis4w7bucllxkmlk91sjgluuag5syphl","state":{"doctype":"tile","content":{},"metadata":{"family":"test","controllers":["did:key:z6MkfZ6S4NVVTEuts8o5xFzRMR8eC6Y1bngoBQNnXiCvhH8H"]},"signature":0,"anchorStatus":"NOT_REQUESTED","log":[{"cid":"bafyreihtdxfb6cpcvomm2c2elm3re2onqaix6frq4nbg45eaqszh5mifre","type":0}]}}
```

**Request 1, unique set to 0**
```sh
curl https://ceramic-clay.3boxlabs.com/api/v0/documents -X POST -d '{
   "doctype": "tile",
   "genesis": {
     "header": {
       "family": "test",
       "controllers": ["did:key:z6MkfZ6S4NVVTEuts8o5xFzRMR8eC6Y1bngoBQNnXiCvhH8H"]
     }, "unique": "0"
   },
   "docOpts": { "publish": false, "anchor": false }
 }' -H "Content-Type: application/json"
 
{"docId":"k2t6wyfsu4pg1788blcx8r48j01eaafwrq349ikskig7qlaq1ql26wxxnnivme","state":{"doctype":"tile","content":{},"metadata":{"family":"test","controllers":["did:key:z6MkfZ6S4NVVTEuts8o5xFzRMR8eC6Y1bngoBQNnXiCvhH8H"]},"signature":0,"anchorStatus":"NOT_REQUESTED","log":[{"cid":"bafyreifvc62lw3c455aycxg6tw3uqepzxsbpw6sqxxuhfu7n7jduhxxtsy","type":0}]}}
```

2021-03-23 14:20 UTC, stbrody commented
I don't understand why those two documents would be expected to have the same DocID, they're different?  A `unique` field with the value of `"0"` is still a unique field, same as if the string was a random sequence of characters

2021-03-23 14:25 UTC, oed commented
> I don't understand why those two documents would be expected to have the same DocID, they're different? A unique field with the value of "0" is still a unique field, same as if the string was a random sequence of characters

That's the problem. Previous versions of ceramic generating a deterministic document would add this field when using the http client. Now if a dev upgrades to a version that uses this PR they would get a different docid. This is not acceptable because it breaks the expectation, not just the structure of the api.

2021-03-23 14:25 UTC, stbrody commented
I guess this goes back to your same comment from https://github.com/ceramicnetwork/js-ceramic/issues/1149.  Like that issue, this is also a breaking change to document state.  So it comes down to whether we're willing to break existing documents on Clay.  To me, one of the main advantages of having a period of time where we're on testnet but not on mainnet is so that we can make breaking changes as we discover them without having to be burdened by backwards compatibility concerns.  The moment mainnet launches every protocol-level change becomes **much** harder, I don't know why we would choose to tie our own hands any earlier than we have to.  Now's our last chance to make final breaking protocol changes before mainnet goes out and we have to do the elaborate backward compatibility dance for every little change and thus accumulate complexity and tech debt until the end of time.  No one should have data they can't afford to lose on the testnet, that's literally the point of the testnet.

2021-03-25 15:46 UTC, oed approved these changes

2021-03-25 15:54 UTC, merged