Addition of Avalanche C-Chain Support
ceramicnetwork/js-ceramic pull request #1157
Opened 2021-03-25 17:48 UTC by kylecbetts

Avalanche is an open-source platform for launching decentralized applications and enterprise blockchain deployments in one interoperable, highly scalable ecosystem.

Avalanche C-Chain uses the CAIP-3 eip155 namespace with two chain IDs:
43113 for Avalanche Fuji Testnet
43114 for Avalanche Mainnet

2021-03-26 11:02 UTC, oed commented
Hey @kylecbetts the `eip155` namespace is already supported by the "ethereum" AuthProvider. There should be no need to add any extra logic here!

2021-03-26 15:23 UTC, kylecbetts commented
So should we still have an AvalancheAuthProvider class that is a subclass of EthereumAuthProvider with no logic, or are you suggesting adding nothing?

2021-03-29 08:51 UTC, oed commented
@kylecbetts yeah, unless there is something that you do differently than the *EthereumAuthProvider* then there is no reason to add duplicate code :)

2021-03-29 19:50 UTC, kylecbetts commented
@oed thanks for your patience, I have changed the implementation of AvalancheAuthProvider to simply inherit everything from EthereumAuthProvider.

2021-03-30 09:34 UTC, oed commented
@kylecbetts I think you might have misunderstood. Seems like this PR is not needed at all if you can just use the *EthereumAuthProvider* directly? There is nothing added here in terms of functionality afaict.

2021-03-30 16:10 UTC, kylecbetts commented
I guess I was just thinking for users of js-ceramic it would eliminate any confusion of wanting to use the Avalanche platform, as they might not know we use the same functionality as the EthereumAuthProvider. I agree nothing here in terms of functionality, just ease of use.

2021-03-30 17:00 UTC, oed requested changes
Ok if that's what we need, then I would just do the suggested change and remove everything else.

2021-03-30 17:00 UTC, oed commented on packages/blockchain-utils-linking/src/index.ts
> +export { AvalancheAuthProvider } from "./avalanche";
```suggestion
export { EthereumAuthProvider as AvalancheAuthProvider } from "./ethereum";
```

2021-03-30 17:22 UTC, kylecbetts commented
@oed Sorry for all the confusion, I do appreciate the help.

2021-04-01 10:09 UTC, oed approved these changes
Thanks @kylecbetts

2021-04-01 10:09 UTC, merged