feat(core): Update pubsub messages to use 'stream' instead of 'doc'
ceramicnetwork/js-ceramic pull request #1291
Opened 2021-04-18 15:59 UTC by stbrody

2021-04-18 17:17 UTC, oed requested changes
This is a protocol breaking change. I think we should wait with this until after ELP and think about a real upgrade path.

2021-04-18 17:39 UTC, stbrody commented
> This is a protocol breaking change. I think we should wait with this until after ELP and think about a real upgrade path.

Well I did include backwards compatibility logic in this, but I guess there's no reason this has to happen now.  We could wait and do this as part of the protocol versioning project as the first live protocol message format update.

2021-04-19 07:59 UTC, oed commented
> Well I did include backwards compatibility logic in this

Did you forget to push this? Definitely no there afaict.

2021-04-19 13:06 UTC, stbrody commented
> > Well I did include backwards compatibility logic in this
> 
> Did you forget to push this? Definitely no there afaict.

It's there.  Check out the `serialize` and `deserialize` functions in pubsub-message.ts

2021-04-19 13:17 UTC, oed approved these changes
Sneaky! Alright my bad. This should be fine then :)

2021-04-19 13:17 UTC, oed commented on packages/core/src/pubsub/pubsub-message.ts
> +        stream: message.stream.toString(),
👀

2021-04-19 17:55 UTC, merged