Renaming "record" to "commit"
ceramicnetwork/js-ceramic pull request #1649
Opened 2021-08-16 19:10 UTC by moh-27

Hi,
this PR is for resolving issue #1070 by renaming the "record" to "commit"

I'm a beginner at this, let me know if I did something wrong so I can edit.
Thanks

2021-08-20 10:32 UTC, ukstv requested changes

2021-08-20 10:32 UTC, ukstv commented on packages/core/src/anchor/ethereum/ethereum-anchor-service.ts
> -        const { anchorRecord } = json
This change would make js-ceramic incompatible with [ceramic-anchor-service](https://github.com/ceramicnetwork/ceramic-anchor-service/blob/develop/src/models/request-presentation.ts#L30). I would advice adding a corresponding PR to ceramic-anchor-service repository to add `anchorCommit` field in addition to the present `anchorRecord` one. Please note: _add_, not _rename_. We want to maintain backwards compatibility.

2021-08-20 10:33 UTC, ukstv commented
Apart from the single requested change related to interaction with ceramic-anchor-service, this thing is good. Good work @moh-27 !

2021-08-28 12:34 UTC, moh-27 commented
Thank you @ukstv for your review. And sorry for the late reply I got really busy.
@oed I'm gonna try doing it by today or tomorrow, and I let you know if I couldn't do it or didn't have time for it.

Thanks

2021-09-01 17:13 UTC, moh-27 commented
Hi @ukstv, I have done the requested changes and already have been [merged](https://github.com/ceramicnetwork/ceramic-anchor-service/pull/492) into the [ceramic-anchor-service](https://github.com/ceramicnetwork/ceramic-anchor-service/blob/develop/src/models/request-presentation.ts) repository.

2021-09-13 20:07 UTC, stbrody commented
LGTM, merging.  Thanks!

2021-09-13 20:07 UTC, merged