add `asDID` option to TileDocumentHandler
ceramicnetwork/js-ceramic pull request #1864
Opened 2021-11-24 01:42 UTC by haardikk21

## Description - #1836 

Introduces the ability to make an update with a different DID `asDID` than the one invoking the call. Necessary for OCAP work that is in-progress where updates will be made by the permission holder rather than the permission giver.

## How Has This Been Tested?

Since OCAPs are not fully implemented yet, there are two basic tests. 

The first passes the Ceramic Api's authenticated DID as `asDID` - which works as expected (even though we do switch to using `asDid` instead of `ceramic` for the signatures) 

The second passes a random DID `asDID` and it fails when attempting to sign a Dag JWS. 

More tests will be added as the CACAO library progresses and real use cases become available to test. The changes made should not affect any existing code flows.

## PR checklist

Before submitting this PR, please make sure:

- [x] I have tagged the relevant reviewers and interested parties
- [-] I have updated the READMEs of affected packages
- [-] I have made corresponding changes to the documentation

2021-11-24 13:40 UTC, ukstv commented on packages/stream-tile/src/tile-document.ts
> +    let signer: CeramicSigner = this.api
Suggestion: `const signer: CeramicSigner = opts.asDID ? { signer: opts.asDID } : this.api`

2021-11-24 13:41 UTC, ukstv commented on packages/common/src/streamopts.ts
> +import { DID } from 'dids'
```suggestion
import type { DID } from 'dids'
```

2021-11-24 13:41 UTC, ukstv commented on packages/canary-integration/src/__tests__/tile-update.test.ts
> +import crypto from 'crypto'
Please, use `@stablelib/random`.

2021-11-24 13:43 UTC, ukstv requested changes
minor changes requested: import type DID, use @stablelib/random

2021-11-24 17:48 UTC, ukstv approved these changes
🏇

2021-11-24 17:49 UTC, merged

2021-12-03 21:38 UTC, stbrody commented
Sorry I'm late to the party here, but why is this necessary?  Why wouldn't we always take the DID that the Ceramic handle is authenticated as?

2021-12-04 01:14 UTC, oed commented
Because you might have two different session keys that have write access
to different streams. Also, check out the spec.

Sent via Superhuman iOS ***@***.***>


On Fri, Dec 3 2021 at 9:39 PM, Spencer T Brody ***@***.***>
wrote:

> Sorry I'm late to the party here, but why is this necessary? Why wouldn't
> we always take the DID that the Ceramic handle is authenticated as?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/ceramicnetwork/js-ceramic/pull/1864#issuecomment-985848149>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA52ONKDIC2OEJZU73WAE2DUPE2HPANCNFSM5IU4G7TQ>
> .
>