Add Solana to Blockchain Utils Validation
ceramicnetwork/js-ceramic pull request #1986
Opened 2022-01-13 11:22 UTC by particlebanana

## Description

Solana had been successfully added as a blockchain with the proper function for validating the link but was missing from the handler index. This meant trying to use the SolanaAuthProvider failed as an unsupported handler.

Being new to the codebase this took me way too long to figure out _why_ the auth provider was failing so I wanted to get it patched for everyone starting to play with Solana.

Followup as I have time in the next few days:
* The Solana Auth Provider needs a few tweaks to support Phantom from my testing. I'll make some patches to ensure the top Solana wallets are covered.
* Add Solana to the UX elements in the Self.id codebases

## How Has This Been Tested?

The actual blockchain validation code is tested but not the index. I have run a local copy and used Solana in development on it successfully.

## PR checklist

Before submitting this PR, please make sure:

- [x] I have tagged the relevant reviewers and interested parties
- [x] I have updated the READMEs of affected packages
- [x] I have made corresponding changes to the documentation

2022-01-15 19:25 UTC, ukstv requested changes

2022-01-15 19:25 UTC, ukstv commented on packages/blockchain-utils-validation/src/index.ts
> +import solana from './blockchains/solana'
```suggestion
import solana from './blockchains/solana.js'
```

2022-01-15 23:02 UTC, particlebanana commented on packages/blockchain-utils-validation/src/index.ts
> +import solana from './blockchains/solana'
@ukstv why is `.js` needed here?

2022-01-18 18:05 UTC, ukstv approved these changes

2022-01-18 18:06 UTC, merged

2022-01-18 18:07 UTC, ukstv commented
Thanks, @particlebanana !!