chore: Use newer go-ipfs
ceramicnetwork/js-ceramic pull request #2058
Opened 2022-02-22 16:23 UTC by ukstv

- Update to go-ipfs v0.12
- It works on Apple Silicon out of the box, no env variables needed.

2022-02-22 17:43 UTC, stbrody approved these changes
ooh awesome.  Great to see this just works out of the box.

FYI @v-stickykeys @smrz2001

2022-02-22 17:45 UTC, oed commented
Note that we will likely remain on 0.11 on our infra for a while since 0.12 does a repo migration.

2022-02-22 17:50 UTC, stbrody commented
> Note that we will likely remain on 0.11 on our infra for a while since 0.12 does a repo migration.
> 
> We don't use this bundle for our infra anyway.

oh interesting... hmm, we may not want to be running our unit tests with version 12 then if our infra is still on v11

2022-02-22 17:51 UTC, stbrody requested changes
revoking my approval - if we're not ready to up our infra to v12 then we should up our testing or what's started by default on the CLI

2022-02-22 18:00 UTC, oed commented
Fwiw, our infra uses https://github.com/ceramicnetwork/go-ipfs-daemon/ not this code. 
0.12 doesn't do any changes to networking, only local data store. I think this is a fairly safe change.
https://github.com/ipfs/go-ipfs/releases/tag/v0.12.0

2022-02-22 18:01 UTC, stbrody commented
> Fwiw, our infra uses [ceramicnetwork/go-ipfs-daemon](https://github.com/ceramicnetwork/go-ipfs-daemon/) not this code. 0.12 doesn't do any changes to networking, only local data store. I think this is a fairly safe change. [ipfs/go-ipfs@`v0.12.0` (release)](https://github.com/ipfs/go-ipfs/releases/tag/v0.12.0)

even so.  as a general rule we shouldn't be testing with something different than what we're running

2022-02-22 21:26 UTC, oed commented
I'm pretty sure our integration tests are using go-ipfs-daemon (or should
be?). Overall though I think let's keep it at 0.11 for now. Once we have
integration test running we can upgrade here more confidently.

*Joel Thorstensson *
Co-founder / CTO
[image: 3Box Labs] <https://3boxlabs.com>

On Tue, Feb 22 2022 at 6:01 PM, Spencer T Brody ***@***.***>
wrote:

> Fwiw, our infra uses ceramicnetwork/go-ipfs-daemon
> <https://github.com/ceramicnetwork/go-ipfs-daemon/> not this code. 0.12
> doesn't do any changes to networking, only local data store. I think this
> is a fairly safe change. ***@***.*** (release)
> <https://github.com/ipfs/go-ipfs/releases/tag/v0.12.0>
>
> even so. as a general rule we shouldn't be testing with something
> different than what we're running
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ceramicnetwork/js-ceramic/pull/2058#issuecomment-1048067023>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA52ONLA46S56NFSEGFTT2DU4PFQTANCNFSM5PB37LRQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-02-23 13:21 UTC, ukstv commented
Valid concern. Converting it to draft.

2022-03-10 20:20 UTC, oed commented
I guess this one is relevant and should be merged now @stbrody @ukstv

2022-03-11 11:10 UTC, merged