feat: Add allowQueriesBeforeHistoricalSync flag to config
ceramicnetwork/js-ceramic pull request #2289
Opened 2022-06-30 13:58 UTC by ukstv

Add allowQueriesBeforeHistoricalSync to index config.

If set to `false`, calls to `/api/v0/collection` return 503 error "Index for historical data is not available".

CLI creates a new daemon config with the flag set to `true`.

For existing config files, if the flag is absent, default is `false`.

2022-07-06 20:17 UTC, stbrody requested changes
as written if you use ceramic `core` directly you can bypass this flag.  Eventually when we actually have historical indexing, we'll need to track the progress of the historical sync for each model separately, so the code that throws this error will need to move down into Ceramic core at that point anyway (since the historical sync may be complete for some models but not others).  Given that sooner or later we're going to have to thread this flag down into Ceramic core, IMO we should go ahead and do that now, putting this check closer to where it will ultimately need to live for the long term.

2022-07-06 20:17 UTC, stbrody commented on packages/cli/src/__tests__/ceramic-daemon.test.ts
> +      indexing: { 'allow-queries-before-historical-sync': allowHistorical },
if `allowHistorical` is false can we remove the `indexing` section entirely, to test the default behavior?

2022-07-07 13:13 UTC, ukstv commented
> Eventually when we actually have historical indexing, we'll need to track the progress of the historical sync for each model separately, so the code that throws this error will need to move down into Ceramic core at that point anyway (since the historical sync may be complete for some models but not others)

Oh, this is what I was afraid of when pushing this. Another scope creep. There is an expected breaking change down the line. If "eventually" this field is per model, then we should change the config file format now, before the release, and this IMO should be reflected in the spec.

2022-07-07 14:17 UTC, stbrody commented
> If "eventually" this field is per model, then we should change the config file format now, before the release, and this IMO should be reflected in the spec.

Sorry, I might not have been clear.  I didn't mean that the config option should be per-model, I agree that should stay global to the instance.  I meant that the status of the historical sync itself will be per-model.  For instance, imagine a node is configured to index models A and B.  The historical sync completes, and now queries on A and B become allowed.  Then the node is told to start indexing model C as well.  The historical sync for C kicks off, and while it is running queries on C should fail, but queries on A and B can continue to work as those models are still in sync.

Does that make sense and seem aligned with your expectations?

2022-07-08 10:27 UTC, ukstv commented
Ah, yes, that makes it much clearer.

2022-07-11 13:28 UTC, ukstv commented
@stbrody I believe, now the error is thrown in the right place.

2022-07-11 14:49 UTC, ukstv commented on packages/cli/src/daemon-config.ts
> +  @jsonMember(Boolean, {
There now.

2022-07-11 19:48 UTC, merged