fix(core): Don't unpin anchor proof or merkle tree when unpinning streams
ceramicnetwork/js-ceramic pull request #2307
Opened 2022-07-07 21:26 UTC by stbrody

This does technically leave some leaked CIDs pinned in IPFS after unpinning a stream, but that seems better to me than accidentally unpinning data that might be in use by other streams

2022-07-11 18:16 UTC, ukstv requested changes
LGTM for the change in the description.

Not quite relevant: Do you think we can leave a capability pinned? There is no guarantee a capability is issued just for a particular stream. Most often it is reused across many streams.

2022-07-11 18:16 UTC, ukstv commented on packages/core/src/store/__tests__/pin-store.test.ts
> +    expect(pinning.unpin.mock.calls[2][0].toString()).toEqual(capCID.toString())
So, we unpin a capability, even if it can be used by some other stream?

2022-07-11 18:27 UTC, stbrody commented
> Do you think we can leave a capability pinned? There is no guarantee a capability is issued just for a particular stream. Most often it is reused across many streams.

Ooh really good catch.  Yeah I'll update this to leave the CACAO alone during unpin, just like I do with the anchor proof and merkle tree

2022-07-13 16:04 UTC, ukstv approved these changes
🏇

2022-07-13 16:18 UTC, merged