feat(indexing,stream-model): Indexing logic for interfaces
ceramicnetwork/js-ceramic pull request #2972
Opened 2023-10-04 09:56 UTC by PaulLeCam

Updates the model definition to support interfaces and adds a new table to track the relations between interfaces and the models implementing them

2023-10-05 15:12 UTC, dbcfd requested changes

2023-10-10 23:01 UTC, stephhuynh18 approved these changes
Just some questions =)

2023-10-11 09:14 UTC, PaulLeCam commented on packages/stream-model/src/codecs.ts
> +    strict({ type: literal('set'), fields: array(string) }),
That's to support the SET account relation in future work, basically the model definition changes here not only include the breaking changes to support interfaces but also the SET account relation.
Regarding `fields` value here if that's your question, it's to identify what content fields should be used to create the set value.

2023-10-11 09:17 UTC, PaulLeCam commented on packages/indexing/src/database-index-api.ts
> +        await trx(MODEL_IMPLEMENTS_TABLE_NAME).insert(modelImplements).onConflict().ignore()
If there is a conflict it's because the interface/implementing model relation already exists, which is what we want with this insertion

2023-10-11 09:33 UTC, PaulLeCam commented on packages/stream-model/src/codecs.ts
> +    strict({ type: literal('relationDocument'), model: optionalModelString, property: string }),
Yes good call, I added to the comment to the `ModelViewDefinitionV2`

2023-10-12 14:43 UTC, dbcfd approved these changes

2023-10-12 14:43 UTC, merged