feat(cli,common,indexing): support interfaces queries
ceramicnetwork/js-ceramic pull request #3011
Opened 2023-10-23 14:30 UTC by PaulLeCam

2023-10-24 15:55 UTC, dbcfd requested changes
Looking at this PR, I'm worried about the interaction of indices and interfaces, and then the impact on the database from trying to query models that implement an interface. It feels like an interface should be a materialized view across multiple model tables, with appropriate indices on the view, so that when queried, you query the fields for the interface. I am not sure otherwise how you would build a query from multiple different models that makes sense to the user.

2023-10-25 08:43 UTC, PaulLeCam commented on packages/indexing/src/database-index-api.ts
> +  getModelInterfaces(modelID: string): Set<string> {
No, good catch. I removed it.

2023-10-25 08:45 UTC, PaulLeCam commented on packages/indexing/src/database-index-api.ts
> +    if (tables.length === 1) {
I didn't know what was Knex' `unionAll` behavior so I expected it would need >=2 items but it works with a single one, I removed this check

2023-10-25 15:52 UTC, dbcfd commented
Per retro, there's two paths forward that would help me commit to moving forward with this PR
* Description of benchmarking to explore performance impacts
* API documentation on what calls and returns look like for queries with models vs queries with interfaces

2023-10-25 16:22 UTC, PaulLeCam commented
>     * Description of benchmarking to explore performance impacts

Seems like this should be a specific project to benchmark queries? Or do we already have something in place that can be used please?

>     * API documentation on what calls and returns look like for queries with models vs queries with interfaces

There's no difference between querying for models or interfaces, either way the inputs are the models/interfaces stream IDs and the results are the matching documents

2023-10-26 15:18 UTC, dbcfd commented
> 
> Seems like this should be a specific project to benchmark queries? Or do we already have something in place that can be used please?
> 

Keramik can be used, but would possibly need to add support to the rust ceramic http client to support creating an interface. This question is more, what would that scenario or scenarios look like.

> There's no difference between querying for models or interfaces, either way the inputs are the models/interfaces stream IDs and the results are the matching documents

So a couple of things
* If we pass in model ids that don't belong to the interface, how do we plan to resolve the results that are from interface vs those that are from non interface model ids?
* If pass in an interface id, do we expect all data from all models to be returned, or just the data matching the interface id?

2023-10-26 15:31 UTC, PaulLeCam commented
> > Seems like this should be a specific project to benchmark queries? Or do we already have something in place that can be used please?
> 
> Keramik can be used, but would possibly need to add support to the rust ceramic http client to support creating an interface. This question is more, what would that scenario or scenarios look like.

OK so indeed that sounds like a different project, no?
I think that would be good to add but shouldn't be in scope of this project itself.

> > There's no difference between querying for models or interfaces, either way the inputs are the models/interfaces stream IDs and the results are the matching documents
> 
> So a couple of things
> 
>     * If we pass in model ids that don't belong to the interface, how do we plan to resolve the results that are from interface vs those that are from non interface model ids?
> 
>     * If pass in an interface id, do we expect all data from all models to be returned, or just the data matching the interface id?

There's no "results from interface" per-se, as interfaces have no associated documents.
If you provide a model ID matching a known interface, internally it gets mapped to the matching indexed models, so the data returned are the documents using models implementing the interface.

2023-10-31 15:15 UTC, dbcfd approved these changes

2023-10-31 15:15 UTC, merged