Feature/Include pushing the different event types
ceramicnetwork/js-ceramic pull request #3126
Opened 2024-01-30 17:36 UTC by JulissaDantes

## Description
Allows to have different event codes for Firehose so that users could perform different actions according to whether an event is triggered by a stream creation, a stream anchoring or a stream update from the user.

2024-01-30 21:38 UTC, stbrody requested changes

2024-01-30 21:38 UTC, stbrody commented on packages/core/src/feed.ts
> +export enum EventType {
I believe the standard names for these from the protocol spec now are Init Events, Data Events, and Time Events.  So presumably that means this enum should have INIT, DATA, and TIME values.

Tagging @oed to confirm.

2024-01-30 21:38 UTC, stbrody commented on packages/core/src/feed.ts
> +  ANCHOR = 1,
toooooottaal nitpick that really doesn't matter at all, but I feel like I'll have an easier time remembering the values these represent if init/create is 0, data/update is 1, and time/anchor is 2.

2024-01-30 21:38 UTC, stbrody commented on packages/core/src/feed.ts
> +    case CommitType.ANCHOR:
why not just use the CommitType enum (and make a change to the names of the values in that enum to match the current naming convention)?  Why have two enums and map between the two of them?

2024-01-30 21:38 UTC, stbrody commented on packages/core/src/feed.ts
> +    default:
this worries me, can we throw an error if the log doesn't have the type set properly?  That would probably indicate a bug in our code if that ever happened.

2024-01-31 14:34 UTC, ukstv approved these changes

2024-01-31 19:58 UTC, merged