Added WebAuthN support to SignatureUtils for Passkey support
ceramicnetwork/js-ceramic pull request #3202
Opened 2024-04-09 20:55 UTC by SnickerChar

## Description

This work was requested as an improvement from the Ceramic developers (Joel Thorstensson) in conjunction with Snickerdoodle Labs. It adds WebAuthN support for DID verification, which will enable Passkey support for DIDs. It just adds the Ceramic authored @didtools/key-webauthn package and wires it into SignatureUtils.

## How Has This Been Tested?

Was not able to test on my local; the test scripts do not seem to work on a Windows machine. CI should catch any problems per devs.

## PR checklist

Before submitting this PR, please make sure:

- [ ] I have tagged the relevant reviewers and interested parties
- [ ] I have updated the READMEs of affected packages
- [ ] I have made corresponding changes to the documentation

2024-04-10 17:06 UTC, ukstv commented on packages/common/package.json
> +    "@didtools/key-webauthn": "^2.0.1",
Please @SnickerChar use ^2.0.2

There is a minor bug in 2.0.1

2024-04-10 17:07 UTC, ukstv requested changes
Please @SnickerChar use ^2.0.2

There is a minor bug in 2.0.1

2024-04-11 00:09 UTC, SnickerChar commented
Updated to 2.0.2

2024-04-15 13:23 UTC, ukstv commented
Hey @SnickerChar the changes are now merged in a different PR: https://github.com/ceramicnetwork/js-ceramic/pull/3208 Had to do that due to some limitation on GH action. Ok to close this PR?

2024-04-15 16:01 UTC, SnickerChar commented
No problem. Closed!

2024-04-15 16:01 UTC, closed without merging