feat: 3id resolve v0 and v1 3ids
ceramicnetwork/js-ceramic pull request #511
Opened 2020-11-17 20:36 UTC by zachferland

2020-11-18 00:41 UTC, zachferland commented
hmm may change this check if cid to resolve v0, otherwise this breaks tests everywhere we are using invalid 3id strings to mock 3ids

2020-11-18 07:45 UTC, oed commented on packages/3id-did-resolver/package.json
> +    "3id-resolver": "^1.0.1",
Can we please not use this?

2020-11-20 02:28 UTC, zachferland commented
"sub" did resolution not added from 3id-resolver given our migration path

2020-11-20 08:07 UTC, oed requested changes
Looks good overall, one main change needed. I also wonder how we can get the v0 docs migrated to our new ipfs infra?

2020-11-20 08:07 UTC, oed commented on packages/3id-did-resolver/src/index.ts
> +    const content =  { metadata: { controllers: [`did:key:${managementKey}`], tags: ['3id'] } }
We can't have a `did:key` that's an ethereumAddress. Therefore in IDW you can see that we use the `signingKey` as the `managementKey` for the genesis record.

2020-11-20 08:07 UTC, oed commented on packages/3id-did-resolver/src/legacyResolver.ts
> +  }
This can be removed as it's never set.

2020-11-20 08:07 UTC, oed commented on packages/3id-did-resolver/src/legacyResolver.ts
> +    }
Don't think we ever used services here, so can probably be removed.

2020-11-20 09:55 UTC, oed commented on packages/3id-did-resolver/src/index.ts
> +    const content =  { metadata: { controllers: [`did:key:${managementKey}`], tags: ['3id'] } }
We should also change it from tags to family: 
```suggestion
    const content =  { metadata: { controllers: [`did:key:${managementKey}`], family: '3id' } }
```
See here: https://github.com/3box/identity-wallet-js/pull/97

2020-11-22 11:55 UTC, oed approved these changes
Looks great. Just one small nitpick.

2020-11-22 11:55 UTC, oed commented on packages/3id-did-resolver/src/index.ts
> +          publicKeyHex: u8a.toString(keyBuf.slice(2), 'base16')
Can we change this to be `publicKeyBase58`? did-jwt is updated to support it!

2020-11-22 11:55 UTC, oed commented on packages/3id-did-resolver/src/index.ts
> +          publicKeyBase64: u8a.toString(keyBuf.slice(2), 'base64')
`publicKeyBase58` here as well!

2020-11-22 11:55 UTC, oed commented on packages/3id-did-resolver/src/__tests__/__snapshots__/index.test.ts.snap
> +      "publicKeyBase64": "N2/yXOxq8FCX4zzht8JQA3ftVRl+6C39CeU82eFB4Ug",
The reason `=` is gone is because you used `base64` instead of `base64pad`.

2020-11-22 11:56 UTC, oed commented
Also fix CI :)

2020-11-24 09:33 UTC, oed approved these changes
Pushed some small changes to how the 3IDv0 document is created. Also updated the mocks to return the same format of documents as created from IDW.

2020-11-24 09:36 UTC, merged