feat: Add support for cosmos blockchain
ceramicnetwork/js-ceramic pull request #824
Opened 2021-01-20 11:42 UTC by stanly-johnson

This PR is a migration of [#44](https://github.com/ceramicnetwork/js-3id-blockchain-utils/pull/44)

**Summary** :
Add support for `cosmos:cosmoshub-3` chain to the library

**Dependencies added** :
Tendermint Signer

**Changes**:
- [X] Add cosmos linking support
- [ ] Add cosmos authentication support
- [ ] Update Docs

2021-01-20 12:20 UTC, stanly-johnson commented
I can only run tests on validation once these changes are merged :)

2021-01-20 12:24 UTC, oed commented
Why @stanly-johnson you should be able to do it now. Just make sure to build the library before!

2021-01-20 12:25 UTC, oed commented
Just do `npm run build` top level and you should be able to import the updated linking library into the validation package.

2021-01-21 10:12 UTC, oed requested changes
Looks pretty good. Left a few suggestions.

2021-01-21 10:12 UTC, oed commented on packages/blockchain-utils-linking/src/cosmos.ts
> +      type: 'cosmos',
We don't need this type since the context that this is cosmos is included in `account`.
```suggestion
```

2021-01-21 10:12 UTC, oed commented on packages/blockchain-utils-linking/src/cosmos.ts
> +const CHAIN_ID = "cosmos:cosmoshub-3";
Should this really be hardcoded? Seems like we'd want to support any cosmos blockchain right?

2021-01-21 10:12 UTC, oed commented on packages/blockchain-utils-linking/src/cosmos.ts
> +    private readonly address: string) {}
Maybe you can pass the chainId (or chain reference, e.g. `cosmoshub-3`) here in the constructor?

2021-01-21 10:12 UTC, oed commented on packages/blockchain-utils-validation/package.json
> +    "@tendermint/sig": "^0.6.0"
This should be a regular dependency right?

2021-01-21 10:12 UTC, oed commented on packages/blockchain-utils-validation/src/blockchains/cosmos.ts
> +import * as linking from "@ceramicnetwork/blockchain-utils-linking";
```suggestion
import type { LinkProof } from "@ceramicnetwork/blockchain-utils-linking";
```
You can just import the type here and use it below.

2021-01-21 13:47 UTC, oed approved these changes
Alright, this looks good. Paging @ukstv for another reivew.

2021-01-21 14:06 UTC, ukstv requested changes
Request DRY fixes for `asTransaction` and `getMetaData`. After that good to go.

2021-01-21 14:06 UTC, ukstv commented on packages/blockchain-utils-linking/src/cosmos.ts
> +function asTransaction(address: string, message: string): Tx {
Export it.

2021-01-21 14:06 UTC, ukstv commented on packages/blockchain-utils-validation/src/blockchains/cosmos.ts
> +function asTransaction(address: string, message: string): Tx {
Use the one exported from linking package, please.

Would be pity, if someone forgets to change this in either linking or validation packages.

2021-01-21 14:06 UTC, ukstv commented on packages/blockchain-utils-validation/src/blockchains/cosmos.ts
> +function getMetaData(): SignMeta {
Reuse from linking, like `asTransaction`.

2021-01-21 14:15 UTC, ukstv commented
Yup, happy now.

2021-01-21 14:15 UTC, ukstv approved these changes

2021-01-21 14:16 UTC, merged